name: Publish to NPM

permissions:
    contents: write

on:
    push:
        tags:
            - '*'

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
              run: npm ci
            - name: Npm Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Github Release
              uses: softprops/action-gh-release@v1
              with:
                  generate_release_notes: true
